apiVersion: v1
kind: ReplicationController
metadata:
  name: myapp-rc
  labels:
    app: myapp-rc
spec:
  template: 
    metadata:
      name: pesho-pg
      labels:
        app: postgres
        tier: db
    spec:
      containers:
        - name: postgres
          image: postgres
          env:
            - name: POSTGRES_PASSWORD
              value: "1234"
  replicas: 3
