apiVersion: v1
kind: Pod
metadata:
  name: pesho-pg
  labels:
    app: postgres
    tier: db
spec:
  containers:
  - name: postgres
    image: postgres
    env:
    - name: POSTGRES_PASSWORD
      value: "1234" 
